name: Package {{ package.name }}

on:
  push:
    paths:
      - ".github/workflows/package-{{ package.name }}.yml"
      - "{{ package.path }}/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install deps
        run: |
          cd {{ package.path }}
          uv sync

      - name: Check formatting
        run: uvx ruff check {{ package.path }}

      - name: Run tests
        run: uv run pytest {{ package.path }}
